const FOCUS_FLOW_V2_CSS = `
html,body{margin:0;min-height:100%;background:#07070a}*{box-sizing:border-box}button,input,select,textarea{font:inherit}button{cursor:pointer}a{color:inherit;text-decoration:none}
.ff2{--bg:#08080b;--panel:#111016;--panel2:#17151d;--line:rgba(255,255,255,.09);--line2:rgba(255,255,255,.14);--gold:#d6b76f;--gold2:#f0d99e;--text:#f7f2ea;--muted:rgba(247,242,234,.62);--muted2:rgba(247,242,234,.42);--ok:#79d7a2;--warn:#e6c371;--bad:#ea919c;min-height:100vh;color:var(--text);font-family:"LINE Seed Sans TH","Noto Sans Thai","Outfit",system-ui,-apple-system,BlinkMacSystemFont,sans-serif;background:radial-gradient(circle at 72% -8%,rgba(214,183,111,.085),transparent 31%),var(--bg);-webkit-font-smoothing:antialiased}.ff2 [hidden]{display:none!important}
.ff2__top{position:sticky;top:0;z-index:40;border-bottom:1px solid var(--line);background:rgba(8,8,11,.9);backdrop-filter:blur(22px)}.ff2__topInner{width:min(1380px,calc(100% - 36px));min-height:72px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:18px}.ff2__brand{display:flex;align-items:center;gap:12px}.ff2__mark{width:42px;height:42px;border:1px solid rgba(214,183,111,.32);border-radius:14px;display:grid;place-items:center;background:rgba(214,183,111,.07);color:var(--gold2);font-weight:950}.ff2__brand b,.ff2__brand small{display:block}.ff2__brand b{font-size:11px;letter-spacing:.12em}.ff2__brand small{margin-top:4px;color:var(--muted2);font-size:8px;letter-spacing:.12em}.ff2__topActions{display:flex;gap:8px;align-items:center}.ff2__connection,.ff2__ghost{min-height:38px;padding:0 12px;border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.025);color:var(--muted);display:inline-flex;align-items:center;gap:8px;font-size:9px;font-weight:850}.ff2__connection i{width:7px;height:7px;border-radius:50%;background:var(--warn)}
.ff2__shell{width:min(1380px,calc(100% - 36px));margin:0 auto;padding:34px 0 54px}.ff2__hero{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;align-items:end}.ff2__eyebrow{margin:0;color:var(--gold);font-size:9px;font-weight:900;letter-spacing:.17em;text-transform:uppercase}.ff2 h1{margin:8px 0 0;font-size:clamp(48px,6vw,82px);line-height:.9;letter-spacing:-.055em}.ff2__lead{max-width:720px;margin:16px 0 0;color:var(--muted);font-size:12px;line-height:1.75}.ff2__heroMeta{text-align:right;color:var(--muted2);font-size:9px;line-height:1.7}.ff2__heroMeta b{display:block;color:var(--gold2);font-size:11px}
.ff2__steps{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin-top:28px;padding:8px;border:1px solid var(--line);border-radius:17px;background:rgba(255,255,255,.018)}.ff2__step{min-height:52px;border:0;border-radius:12px;background:transparent;color:var(--muted2);text-align:left;padding:9px 11px;display:grid;grid-template-columns:24px 1fr;gap:8px;align-items:center}.ff2__step i{width:24px;height:24px;border:1px solid var(--line);border-radius:50%;display:grid;place-items:center;font-style:normal;font-size:8px}.ff2__step b{font-size:10px}.ff2__step small{display:block;margin-top:2px;font-size:7px;font-weight:600}.ff2__step.is-active{background:rgba(214,183,111,.08);color:var(--text)}.ff2__step.is-active i{border-color:rgba(214,183,111,.48);background:var(--gold);color:#18120a}.ff2__step.is-complete{color:var(--muted)}.ff2__step.is-complete i{border-color:rgba(121,215,162,.3);color:var(--ok)}.ff2__step.is-locked{opacity:.42;cursor:default}
.ff2__layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:14px;margin-top:14px;align-items:start}.ff2__flow{display:grid;gap:10px}.ff2__stage{border:1px solid var(--line);border-radius:22px;background:linear-gradient(180deg,rgba(255,255,255,.022),rgba(255,255,255,.008)),var(--panel);overflow:hidden;transition:border-color .2s ease,background .2s ease,opacity .2s ease}.ff2__stage.is-current{border-color:rgba(214,183,111,.32);background:linear-gradient(180deg,rgba(214,183,111,.035),rgba(255,255,255,.008)),var(--panel)}.ff2__stage.is-locked{opacity:.48}.ff2__stageHead{min-height:78px;padding:17px 19px;display:grid;grid-template-columns:34px minmax(0,1fr) auto;gap:12px;align-items:center}.ff2__stageNo{width:34px;height:34px;border:1px solid var(--line);border-radius:50%;display:grid;place-items:center;color:var(--muted2);font-size:9px;font-weight:900}.ff2__stage.is-current .ff2__stageNo{background:var(--gold);border-color:var(--gold);color:#19130b}.ff2__stageTitle b,.ff2__stageTitle small{display:block}.ff2__stageTitle b{font-size:14px}.ff2__stageTitle small{margin-top:5px;color:var(--muted2);font-size:9px;line-height:1.45}.ff2__stageSummary{color:var(--gold2)!important}.ff2__change{min-height:34px;padding:0 11px;border:1px solid var(--line);border-radius:999px;background:transparent;color:var(--muted);font-size:8px;font-weight:900}.ff2__stageBody{display:none;padding:0 19px 20px}.ff2__stage.is-current .ff2__stageBody,.ff2__stage.is-expanded .ff2__stageBody{display:block}.ff2__stage.is-complete:not(.is-current):not(.is-expanded) .ff2__stageHead{min-height:64px}.ff2__stage.is-locked .ff2__change{display:none}
.ff2__sectionLabel{margin:2px 0 10px;color:var(--gold);font-size:8px;font-weight:900;letter-spacing:.13em;text-transform:uppercase}.ff2__search{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.ff2__input,.ff2__select,.ff2__textarea{width:100%;min-height:48px;border:1px solid var(--line2);border-radius:14px;background:rgba(0,0,0,.34);color:var(--text);padding:0 13px;outline:none}.ff2__textarea{min-height:96px;padding:12px 13px;resize:vertical;line-height:1.55}.ff2__input:focus,.ff2__select:focus,.ff2__textarea:focus{border-color:rgba(214,183,111,.48);box-shadow:0 0 0 3px rgba(214,183,111,.06)}.ff2__btn{min-height:42px;padding:0 14px;border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.028);color:var(--text);font-size:9px;font-weight:900}.ff2__btn--gold{border:0;background:linear-gradient(90deg,#a98346,#e2c57c);color:#17120d}.ff2__btn:disabled{opacity:.35;cursor:not-allowed}.ff2__actions,.ff2__chips{display:flex;gap:7px;flex-wrap:wrap}.ff2__chips{margin-top:9px}.ff2__chip{min-height:29px;padding:0 9px;border:1px solid var(--line);border-radius:999px;background:transparent;color:var(--muted2);font-size:8px}.ff2__results{display:grid;gap:7px;margin-top:12px}.ff2__picked{display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:11px;align-items:center;margin-top:12px;padding:13px;border:1px solid var(--line);border-radius:16px;background:rgba(255,255,255,.018)}.ff2__avatar{width:44px;height:44px;border:1px solid rgba(214,183,111,.25);border-radius:14px;display:grid;place-items:center;color:var(--gold2);background:rgba(214,183,111,.06);font-weight:950}.ff2__picked b,.ff2__picked span{display:block}.ff2__picked b{font-size:12px}.ff2__picked span{margin-top:4px;color:var(--muted2);font-size:8px}.ff2__badge{min-height:28px;padding:0 9px;border:1px solid var(--line);border-radius:999px;display:inline-flex;align-items:center;color:var(--muted2);font-size:8px;font-weight:900}
.ff2__choiceGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ff2__choice,.mmdop__folder{min-height:124px;padding:16px;border:1px solid var(--line);border-radius:17px;background:rgba(255,255,255,.018);color:var(--text);text-align:left}.ff2__choice span,.mmdop__folder span{display:block;color:var(--gold);font-size:7px;font-weight:900;letter-spacing:.13em;text-transform:uppercase}.ff2__choice strong,.mmdop__folder strong{display:block;margin-top:9px;font-size:22px;line-height:1}.ff2__choice p,.mmdop__folder p{margin:8px 0 0;color:var(--muted2);font-size:8px;line-height:1.45}.mmdop__folder em{display:inline-flex;margin-top:10px;color:var(--gold2);font-size:8px;font-style:normal;font-weight:900}.ff2__choice.is-selected,.mmdop__folder.is-selected{border-color:rgba(214,183,111,.5);background:rgba(214,183,111,.07)}.ff2__folderGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:8px}.ff2__helper{margin:9px 0 0;color:var(--muted2);font-size:8px;line-height:1.5}.ff2__modelLine{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:end}.ff2__modelPreview{margin-top:10px}
.ff2__fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.ff2__fields--4{grid-template-columns:repeat(4,minmax(0,1fr))}.ff2__field{display:grid;gap:6px}.ff2__field span{color:var(--muted);font-size:8px;font-weight:800}.ff2__field--wide{grid-column:1/-1}.ff2__details{margin-top:10px;border-top:1px solid var(--line);padding-top:10px}.ff2__details summary{list-style:none;cursor:pointer;color:var(--muted);font-size:9px;font-weight:850}.ff2__details summary::-webkit-details-marker{display:none}.ff2__details summary:before{content:'+';display:inline-grid;width:20px;height:20px;margin-right:7px;border:1px solid var(--line);border-radius:50%;place-items:center;color:var(--gold)}.ff2__details[open] summary:before{content:'−'}.ff2__detailsBody{padding-top:12px}.ff2__notice{margin-top:10px;padding:11px 12px;border:1px solid var(--line);border-radius:13px;background:rgba(255,255,255,.018);color:var(--muted2);font-size:8px;line-height:1.55}
.ff2__summary{position:sticky;top:88px;padding:17px;border:1px solid var(--line);border-radius:20px;background:rgba(17,16,22,.92);backdrop-filter:blur(18px)}.ff2__summaryHead span{display:block;color:var(--gold);font-size:8px;font-weight:900;letter-spacing:.13em;text-transform:uppercase}.ff2__summaryHead b{display:block;margin-top:6px;font-size:20px}.ff2__summaryList{display:grid;margin-top:13px}.ff2__summaryRow{display:grid;grid-template-columns:78px minmax(0,1fr);gap:8px;padding:9px 0;border-bottom:1px solid var(--line)}.ff2__summaryRow:last-child{border-bottom:0}.ff2__summaryRow span{color:var(--muted2);font-size:8px}.ff2__summaryRow b{font-size:9px;text-align:right;word-break:break-word}.ff2__next{margin-top:12px;padding:12px;border:1px solid rgba(214,183,111,.2);border-radius:14px;background:rgba(214,183,111,.035)}.ff2__next small,.ff2__next b,.ff2__next span{display:block}.ff2__next small{color:var(--gold);font-size:7px;font-weight:900;letter-spacing:.12em}.ff2__next b{margin-top:6px;font-size:12px}.ff2__next span{margin-top:5px;color:var(--muted2);font-size:8px;line-height:1.45}.ff2__status{margin-top:9px;color:var(--muted2);font-size:8px;line-height:1.45}
.ff2__review{display:grid;gap:9px}.ff2__ready{padding:13px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.018)}.ff2__ready b,.ff2__ready span{display:block}.ff2__ready b{font-size:12px}.ff2__ready span{margin-top:5px;color:var(--muted2);font-size:8px;line-height:1.5}.ff2__reviewGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.ff2__reviewGrid div{padding:11px;border:1px solid var(--line);border-radius:13px;background:rgba(255,255,255,.015)}.ff2__reviewGrid span,.ff2__reviewGrid b{display:block}.ff2__reviewGrid span{color:var(--muted2);font-size:7px}.ff2__reviewGrid b{margin-top:5px;font-size:10px}.ff2__reviewActions{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:4px}.ff2__reviewActions .ff2__btn--gold{min-width:180px}.ff2__output{margin-top:10px;padding:18px;border:1px solid rgba(121,215,162,.22);border-radius:20px;background:rgba(121,215,162,.025)}.ff2__output h3{margin:0;font-size:24px}.ff2__outputGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:12px}.ff2__outputGrid div{padding:11px;border:1px solid var(--line);border-radius:13px}.ff2__outputGrid span,.ff2__outputGrid b{display:block}.ff2__outputGrid span{color:var(--muted2);font-size:7px}.ff2__outputGrid b{margin-top:5px;font-size:9px;word-break:break-word}.ff2__urlGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:10px}
.ff2__systemHooks{display:none!important}.is-ok{border-color:rgba(121,215,162,.28)!important;color:#dff7e8!important}.is-warn{border-color:rgba(230,195,113,.28)!important;color:var(--gold2)!important}.is-bad{border-color:rgba(234,145,156,.3)!important;color:#ffdce1!important}.ff2__connection.is-ok i{background:var(--ok)}.ff2__connection.is-bad i{background:var(--bad)}
.ff2 .mmdop__empty{min-height:74px;padding:15px;border:1px dashed var(--line);border-radius:14px;display:grid;place-items:center;color:var(--muted2);text-align:center;font-size:8px}.ff2 .mmdop__clientCard,.ff2 .mmdop__modelCard{width:100%;display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:11px;align-items:center;padding:12px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.015);color:var(--text);text-align:left}.ff2 .mmdop__clientCard.is-selected{border-color:rgba(214,183,111,.46);background:rgba(214,183,111,.05)}.ff2 .mmdop__clientAvatar,.ff2 .mmdop__modelIcon{width:44px;height:44px;border:1px solid rgba(214,183,111,.22);border-radius:14px;display:grid;place-items:center;color:var(--gold2);background:rgba(214,183,111,.05);font-weight:950}.ff2 .mmdop__clientMain strong,.ff2 .mmdop__modelCard strong{display:block;font-size:11px}.ff2 .mmdop__clientMain span,.ff2 .mmdop__modelCard span{display:block;margin-top:3px;color:var(--muted2);font-size:7px;line-height:1.4}.ff2 .mmdop__tags{display:flex;justify-content:flex-end;gap:4px;flex-wrap:wrap}.ff2 .mmdop__tag{min-height:22px;padding:0 7px;border:1px solid var(--line);border-radius:999px;display:inline-flex;align-items:center;color:var(--muted2);font-size:7px;font-weight:800}.ff2 .mmdop__tag--gold{color:var(--gold2);border-color:rgba(214,183,111,.25)}.ff2 .mmdop__tag--green{color:#dff7e8;border-color:rgba(121,215,162,.24)}.ff2 .mmdop__modelCard b{color:var(--gold);font-size:8px}
@media(max-width:1040px){.ff2__layout{grid-template-columns:1fr}.ff2__summary{position:relative;top:auto;order:-1}.ff2__summaryList{grid-template-columns:repeat(3,1fr);gap:7px}.ff2__summaryRow{display:block;padding:9px;border:1px solid var(--line);border-radius:12px}.ff2__summaryRow b{display:block;margin-top:4px;text-align:left}.ff2__hero{grid-template-columns:1fr}.ff2__heroMeta{text-align:left}.ff2__outputGrid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:700px){.ff2__topInner,.ff2__shell{width:min(100% - 22px,1380px)}.ff2__topActions .ff2__ghost{display:none}.ff2__shell{padding-top:22px}.ff2 h1{font-size:49px}.ff2__steps{display:flex;overflow:auto}.ff2__step{min-width:128px}.ff2__stageHead{grid-template-columns:32px minmax(0,1fr) auto;padding:14px}.ff2__stageBody{padding:0 14px 16px}.ff2__choiceGrid,.ff2__folderGrid,.ff2__fields,.ff2__fields--4,.ff2__reviewGrid,.ff2__urlGrid,.ff2__summaryList,.ff2__outputGrid{grid-template-columns:1fr}.ff2__modelLine,.ff2__search{grid-template-columns:1fr}.ff2__picked,.ff2 .mmdop__clientCard,.ff2 .mmdop__modelCard{grid-template-columns:44px 1fr}.ff2 .mmdop__tags{grid-column:1/-1;justify-content:flex-start}.ff2__reviewActions{display:grid}.ff2__reviewActions .ff2__btn--gold{width:100%}}
`;

const BODY = `<section class="ff2" data-mmd-create-session-pro data-focus-flow-v2 data-admin-base="">
  <header class="ff2__top"><div class="ff2__topInner">
    <a class="ff2__brand" href="/internal/admin/control-room"><span class="ff2__mark">M</span><span><b>MMD PRIVÉ</b><small>OWNER OPERATIONS · FOCUS FLOW V2</small></span></a>
    <div class="ff2__topActions"><button class="ff2__ghost" type="button" data-op-check-session>Check Session</button><span class="ff2__connection" data-op-connection><i></i><span>Checking</span></span></div>
  </div></header>
  <main class="ff2__shell">
    <section class="ff2__hero"><div><p class="ff2__eyebrow">Create Session · Focus Flow v2</p><h1>ทีละอย่าง.<br/>ไม่ต้องเห็นทุกอย่างพร้อมกัน.</h1><p class="ff2__lead">Client → Work → Model → Details → Review. ระบบสิทธิ์, lineage, Telegram gate และ backend authority ยังทำงานเหมือนเดิม แต่ technical detail จะไม่แย่งสายตาจากงานหลัก.</p></div><div class="ff2__heroMeta"><b>CALM OPERATOR SURFACE</b>Current backend · current entitlement · no authority rollback</div></section>

    <nav class="ff2__steps" aria-label="Create Session steps">
      <button class="ff2__step is-active" type="button" data-focus-goto="client"><i>01</i><span><b>Client</b><small>หาและยืนยันลูกค้า</small></span></button>
      <button class="ff2__step is-locked" type="button" data-focus-goto="work"><i>02</i><span><b>Work</b><small>ประเภทงานและ lane</small></span></button>
      <button class="ff2__step is-locked" type="button" data-focus-goto="model"><i>03</i><span><b>Model</b><small>เลือกจาก pool ที่ได้สิทธิ์</small></span></button>
      <button class="ff2__step is-locked" type="button" data-focus-goto="details"><i>04</i><span><b>Details</b><small>เวลา สถานที่ ราคา</small></span></button>
      <button class="ff2__step is-locked" type="button" data-focus-goto="review"><i>05</i><span><b>Review</b><small>ตรวจแล้วค่อย Create</small></span></button>
    </nav>

    <div class="ff2__layout">
      <div class="ff2__flow">
        <section class="ff2__stage is-current" id="client-search" data-focus-section="client">
          <header class="ff2__stageHead"><span class="ff2__stageNo">01</span><div class="ff2__stageTitle"><b>ลูกค้าคนนี้คือใคร?</b><small data-focus-stage-summary="client">ค้นจากชื่อ / LINE / package / legacy tag</small></div><button class="ff2__change" type="button" data-focus-change="client">Change</button></header>
          <div class="ff2__stageBody">
            <div class="ff2__search"><input class="ff2__input" type="text" placeholder="ชื่อเล่น / LINE / เบอร์ / package / tag" data-op-client-query /><button class="ff2__btn ff2__btn--gold" type="button" data-op-search-client>Search</button></div>
            <div class="ff2__chips"><button class="ff2__chip" type="button" data-op-load-recent>Recent</button><button class="ff2__chip" type="button" data-op-quick-query="#purchased">Purchased</button><button class="ff2__chip" type="button" data-op-quick-query="premium">Premium</button><button class="ff2__chip" type="button" data-op-quick-query="-vip-">VIP</button><button class="ff2__chip" type="button" data-op-demo-client>Demo</button><span class="ff2__chip" data-op-search-mode>Cloud</span></div>
            <div class="ff2__results" data-op-client-results><div class="mmdop__empty">เริ่มจากค้นหาลูกค้าหนึ่งคน</div></div>
            <div class="ff2__picked"><span class="ff2__avatar" data-op-client-initial>C</span><div><b data-op-selected-client-name>-</b><span data-op-selected-client-meta>-</span></div><span class="ff2__badge" data-op-selected-confidence>-</span></div>
            <div class="ff2__notice"><span class="ff2__badge" data-op-lineage-badge>Not selected</span><div data-op-lineage-notice style="margin-top:7px">ยังไม่ได้เลือกลูกค้า</div></div>
            <details class="ff2__details"><summary>รายละเอียดระบบของ Client</summary><div class="ff2__detailsBody ff2__fields ff2__fields--4"><label class="ff2__field"><span>Client name</span><input class="ff2__input" data-op-client-name /></label><label class="ff2__field"><span>Username</span><input class="ff2__input" data-op-username /></label><label class="ff2__field"><span>Package / tier</span><input class="ff2__input" data-op-package readonly /></label><label class="ff2__field"><span>Membership</span><input class="ff2__input" data-op-membership-status readonly /></label><label class="ff2__field"><span>LINE display</span><input class="ff2__input" data-op-line-display readonly /></label><label class="ff2__field"><span>LINE user ID</span><input class="ff2__input" data-op-line-user-id readonly /></label><label class="ff2__field"><span>LINE record</span><input class="ff2__input" data-op-line-record-id readonly /></label><label class="ff2__field"><span>Legacy tags</span><input class="ff2__input" data-op-legacy-tags readonly /></label></div></details>
          </div>
        </section>

        <section class="ff2__stage is-locked" id="work-panel" data-focus-section="work">
          <header class="ff2__stageHead"><span class="ff2__stageNo">02</span><div class="ff2__stageTitle"><b>งานนี้เป็นงานแบบไหน?</b><small data-focus-stage-summary="work">เลือก Public หรือ Private แล้วค่อยเลือก lane</small></div><button class="ff2__change" type="button" data-focus-change="work">Change</button></header>
          <div class="ff2__stageBody">
            <div class="ff2__choiceGrid"><button class="ff2__choice" type="button" data-op-work-type="public"><span>PUBLIC WORK</span><strong>Public</strong><p>Travel / Extreme และ public-facing session</p></button><button class="ff2__choice" type="button" data-op-work-type="private"><span>PRIVATE WORK</span><strong>Private</strong><p>Entitlement-aware private folders; fail closed</p></button></div>
            <p class="ff2__helper" data-op-folder-helper>เลือกประเภทงานก่อน</p><div class="ff2__folderGrid" data-op-folder-grid><div class="mmdop__empty">เลือก Public หรือ Private ก่อน</div></div>
          </div>
        </section>

        <section class="ff2__stage is-locked" id="model-panel" data-focus-section="model">
          <header class="ff2__stageHead"><span class="ff2__stageNo">03</span><div class="ff2__stageTitle"><b>เลือก Model</b><small data-focus-stage-summary="model">ระบบจะแสดงเฉพาะ pool ที่ตรงกับ lane</small></div><button class="ff2__change" type="button" data-focus-change="model">Change</button></header>
          <div class="ff2__stageBody"><div class="ff2__modelLine"><label class="ff2__field"><span>Model</span><select class="ff2__select" data-op-model-select><option value="">เลือก lane ก่อน</option></select></label><button class="ff2__btn" type="button" data-op-refresh-models>Refresh</button></div><p class="ff2__helper">Pool · <span data-op-model-rule>-</span></p><div class="ff2__modelPreview" data-op-model-preview><div class="mmdop__empty">ยังไม่ได้เลือก Model</div></div><details class="ff2__details"><summary>รายละเอียด Model pool</summary><div class="ff2__detailsBody ff2__fields"><label class="ff2__field"><span>Lookup key</span><input class="ff2__input" data-op-model-lookup-key readonly /></label><label class="ff2__field"><span>Pool</span><input class="ff2__input" data-op-model-pool readonly /></label></div></details></div>
        </section>

        <section class="ff2__stage is-locked" id="gate-panel" data-focus-section="details">
          <header class="ff2__stageHead"><span class="ff2__stageNo">04</span><div class="ff2__stageTitle"><b>รายละเอียด Session</b><small data-focus-stage-summary="details">วัน เวลา สถานที่ ราคา — technical gates พับไว้ด้านล่าง</small></div><button class="ff2__change" type="button" data-focus-change="details">Change</button></header>
          <div class="ff2__stageBody">
            <div class="ff2__fields ff2__fields--4"><label class="ff2__field"><span>Date</span><input class="ff2__input" type="date" data-op-date /></label><label class="ff2__field"><span>Start</span><input class="ff2__input" type="time" data-op-start /></label><label class="ff2__field"><span>Duration</span><select class="ff2__select" data-op-duration></select></label><label class="ff2__field"><span>End</span><input class="ff2__input" data-op-end readonly /></label><label class="ff2__field ff2__field--wide"><span>Location</span><input class="ff2__input" data-op-location placeholder="สถานที่" /></label><label class="ff2__field ff2__field--wide"><span>Google Maps</span><input class="ff2__input" data-op-map placeholder="https://maps..." /></label><label class="ff2__field"><span>Amount (THB)</span><input class="ff2__input" type="number" min="1" inputmode="numeric" data-op-amount /></label><label class="ff2__field"><span>Payment</span><select class="ff2__select" data-op-payment-type><option value="full">Full</option><option value="deposit">Deposit</option></select></label><label class="ff2__field"><span>Method</span><select class="ff2__select" data-op-payment-method><option value="promptpay">PromptPay</option><option value="transfer">Transfer</option><option value="cash">Cash</option></select></label><label class="ff2__field"><span>Points</span><select class="ff2__select" data-op-points-mode><option value="auto">Auto</option><option value="manual">Manual</option><option value="none">None</option></select></label></div>
            <details class="ff2__details" data-focus-private-details><summary>Private / Telegram Gate</summary><div class="ff2__detailsBody"><div class="ff2__fields ff2__fields--4"><label class="ff2__field"><span>Customer Telegram</span><input class="ff2__input" data-op-customer-telegram /></label><label class="ff2__field"><span>Status</span><select class="ff2__select" data-op-customer-telegram-status><option value="missing">Missing</option><option value="invited">Invited</option><option value="linked">Linked</option><option value="verified">Verified</option></select></label><label class="ff2__field"><span>Model Telegram</span><input class="ff2__input" data-op-model-telegram /></label><label class="ff2__field"><span>Status</span><select class="ff2__select" data-op-model-telegram-status><option value="missing">Missing</option><option value="linked">Linked</option><option value="verified">Verified</option></select></label></div><div class="ff2__notice"><b data-op-gate-label>Waiting</b><div data-op-gate-notice style="margin-top:5px">ระบบจะตรวจ gate ตามประเภทงาน</div></div><label class="ff2__field" style="margin-top:10px"><span>Private handling note</span><textarea class="ff2__textarea" data-op-handling-note></textarea></label></div></details>
            <details class="ff2__details"><summary>Operator / internal details</summary><div class="ff2__detailsBody ff2__fields"><label class="ff2__field"><span>Assigned assistant</span><select class="ff2__select" data-op-human-assistant><option value="Ewvon">Ewvon</option><option value="Boss Per">Boss Per</option></select></label><label class="ff2__field"><span>Escalation owner</span><select class="ff2__select" data-op-escalation-owner><option value="Boss Per">Boss Per</option><option value="Ewvon">Ewvon</option></select></label><label class="ff2__field ff2__field--wide"><span>Operation note</span><textarea class="ff2__textarea" data-op-note></textarea></label></div></details>
          </div>
        </section>

        <section class="ff2__stage is-locked" data-focus-section="review">
          <header class="ff2__stageHead"><span class="ff2__stageNo">05</span><div class="ff2__stageTitle"><b>Review แล้วค่อย Create</b><small data-focus-stage-summary="review">ปุ่ม Create จะเปิดเมื่อข้อมูลที่จำเป็นครบเท่านั้น</small></div><button class="ff2__change" type="button" data-focus-change="review">Review</button></header>
          <div class="ff2__stageBody"><div class="ff2__review"><div class="ff2__reviewGrid"><div><span>CLIENT</span><b data-focus-review="client">-</b></div><div><span>WORK</span><b data-focus-review="work">-</b></div><div><span>MODEL</span><b data-focus-review="model">-</b></div><div><span>GATE</span><b data-focus-review="gate">-</b></div></div><div class="ff2__ready"><b data-op-ready-label>กำลังตรวจความพร้อม</b><span data-op-ready-copy>กรอกข้อมูลทีละขั้น</span></div><div class="ff2__reviewActions"><div class="ff2__actions"><button class="ff2__btn" type="button" data-op-save-draft>Save Draft</button><button class="ff2__btn" type="button" data-op-fill-demo-job>Fill Demo</button></div><button class="ff2__btn ff2__btn--gold" type="button" data-op-create disabled>CREATE SESSION</button></div></div><button class="ff2__btn" type="button" data-op-debug-toggle hidden style="margin-top:10px">Debug</button><details class="ff2__details" data-op-debug-panel hidden><summary>Payload</summary><pre data-op-payload>{}</pre></details></div>
        </section>

        <section class="ff2__output" data-op-output hidden><p class="ff2__eyebrow">Created</p><h3>Session พร้อมแล้ว</h3><div class="ff2__outputGrid"><div><span>SESSION ID</span><b data-op-out-session-id>-</b></div><div><span>PAYMENT REF</span><b data-op-out-payment-ref>-</b></div><div><span>LINE</span><b data-op-out-line-status>-</b></div><div><span>TELEGRAM</span><b data-op-out-telegram-status>-</b></div></div><div class="ff2__urlGrid"><label class="ff2__field"><span>Customer confirmation</span><input class="ff2__input" data-op-out-customer-url readonly /></label><label class="ff2__field"><span>Model confirmation</span><input class="ff2__input" data-op-out-model-url readonly /></label><label class="ff2__field"><span>Member return</span><input class="ff2__input" data-op-out-member-url readonly /></label><label class="ff2__field"><span>Model return</span><input class="ff2__input" data-op-out-model-return-url readonly /></label></div><div class="ff2__actions" style="margin-top:10px"><button class="ff2__btn" type="button" data-op-copy-customer-link>Copy customer link</button><button class="ff2__btn" type="button" data-op-copy-model-link>Copy model link</button><button class="ff2__btn" type="button" data-op-push-line>Send customer LINE</button><button class="ff2__btn ff2__btn--gold" type="button" data-op-new>New Session</button></div><details class="ff2__details"><summary>Messages</summary><div class="ff2__detailsBody ff2__fields"><label class="ff2__field"><span>Customer message</span><textarea class="ff2__textarea" data-op-out-customer-message></textarea><button class="ff2__btn" type="button" data-op-copy-customer-msg>Copy</button></label><label class="ff2__field"><span>Model message</span><textarea class="ff2__textarea" data-op-out-model-message></textarea><button class="ff2__btn" type="button" data-op-copy-model-msg>Copy</button></label></div></details></section>
      </div>

      <aside class="ff2__summary"><div class="ff2__summaryHead"><span>SESSION SUMMARY</span><b>เห็นแค่สิ่งที่ต้องจำ</b></div><div class="ff2__summaryList"><div class="ff2__summaryRow"><span>Client</span><b data-op-stat-client>-</b></div><div class="ff2__summaryRow"><span>Package</span><b data-op-stat-package>-</b></div><div class="ff2__summaryRow"><span>Work</span><b data-op-stat-work>-</b></div><div class="ff2__summaryRow"><span>Lane</span><b data-op-stat-folder>-</b></div><div class="ff2__summaryRow"><span>Model</span><b data-op-stat-model>-</b></div><div class="ff2__summaryRow"><span>Gate</span><b data-op-stat-gate>-</b></div><div class="ff2__summaryRow"><span>Status</span><b data-op-stat-status>Not ready</b></div></div><div class="ff2__next"><small>NEXT</small><b data-op-next-action>Find Client</b><span data-op-next-copy>ค้นลูกค้าก่อน</span></div><div class="ff2__status" data-op-status>กำลังตรวจระบบ</div><div class="ff2__systemHooks"><span data-op-rail-folder>-</span><span data-op-rail-folder-copy>-</span><i data-op-hook="auth"></i><i data-op-hook="lineage"></i><i data-op-hook="models"></i><i data-op-hook="create"></i><i data-op-hook="push"></i></div></aside>
    </div>
  </main>
</section>`;

export function renderCreateSessionFocusFlowV2(): Response {
  const html = `<!doctype html><html lang="th"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="robots" content="noindex,nofollow"/><meta name="theme-color" content="#08080b"/><title>MMD Privé · Create Session · Focus Flow v2</title><style>${FOCUS_FLOW_V2_CSS}</style></head><body>${BODY}<script>window.MMD_CREATE_SESSION_CONFIG={adminBase:location.origin};</script><script src="/a/create-session.js?v=focus-flow-v2-core" defer></script><script src="/a/create-session-focus-flow-v2.js?v=2" defer></script></body></html>`;
  return new Response(html,{status:200,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store, private, max-age=0","x-mmd-create-session-ui":"focus-flow-v2-latest","x-mmd-create-session-authority":"canonical-backend"}});
}
