export const CUSTOMER_IDENTITY_ALIGNMENT_CLIENT = String.raw`(()=>{'use strict';
const PATH='/internal/admin/customer-data',INTEL='/v1/admin/clients/intelligence';if((location.pathname.replace(/\/+$/,'')||'/')!==PATH)return;if(document.querySelector('[data-mmd-identity-alignment-runtime]'))return;const root=document.querySelector('.c360');if(!root)return;
const marker=document.createElement('i');marker.hidden=true;marker.dataset.mmdIdentityAlignmentRuntime='v1';root.appendChild(marker);const q=(s,r=document)=>r.querySelector(s),txt=v=>String(v??'').trim(),esc=v=>txt(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const login=()=>'/internal/admin/login?next='+encodeURIComponent(location.pathname+location.search);
async function api(path){const r=await fetch(path,{credentials:'include',cache:'no-store',headers:{Accept:'application/json'}}),body=await r.text();let d={};try{d=body?JSON.parse(body):{}}catch{}if(r.status===401||r.status===403){location.href=login();throw Error('session_required')}if(!r.ok||d.ok===false)throw Error(d.error||d.message||('HTTP '+r.status));return d}
const style=document.createElement('style');style.textContent='[data-mmd-identity-alignment]{margin-top:10px;padding:12px;border:1px solid #3a3021;border-radius:10px;background:#090806}[data-mmd-identity-alignment] .ia-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}[data-mmd-identity-alignment] .ia-head b{color:#e5cf9b;font-size:10px}[data-mmd-identity-alignment] .ia-state{padding:4px 7px;border:1px solid #3a3021;border-radius:999px;color:#d9a85b;font-size:7px;font-weight:800}[data-mmd-identity-alignment] .ia-state.good{border-color:#36513a;color:#91c986}[data-mmd-identity-alignment] .ia-state.bad{border-color:#613831;color:#dc9084}[data-mmd-identity-alignment] .ia-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:9px}[data-mmd-identity-alignment] .ia-card{padding:9px;border:1px solid #282117;border-radius:8px;background:#0b0907}[data-mmd-identity-alignment] .ia-card span{display:block;color:#806c48;font-size:6.5px}[data-mmd-identity-alignment] .ia-card strong{display:block;margin-top:4px;font-size:9px;word-break:break-word}[data-mmd-identity-alignment] .ia-card small{display:block;margin-top:4px;color:#766f65;font-size:7px;line-height:1.45}[data-mmd-identity-alignment] .ia-note{margin-top:8px;color:#81796e;font-size:7px;line-height:1.5}[data-mmd-identity-alignment] .ia-note b{color:#d9b86c}@media(max-width:640px){[data-mmd-identity-alignment] .ia-grid{grid-template-columns:1fr}}';document.head.appendChild(style);
const panel=document.createElement('section');panel.dataset.mmdIdentityAlignment='v1';panel.innerHTML='<div class="ia-head"><div><b>IDENTITY ALIGNMENT</b><div style="margin-top:4px;color:#81796e;font-size:7px">MY MMD / LIFF ↔ LINE OFC ↔ Canonical Client</div></div><span class="ia-state" data-ia-state>WAITING</span></div><div class="ia-grid"><article class="ia-card"><span>MY MMD / LIFF</span><strong data-ia-liff>—</strong><small data-ia-liff-tail>—</small></article><article class="ia-card"><span>LINE OFC</span><strong data-ia-ofc>—</strong><small data-ia-ofc-tail>—</small></article><article class="ia-card"><span>CANONICAL CLIENT</span><strong data-ia-client>—</strong><small data-ia-client-tail>—</small></article></div><div class="ia-note"><b>Read-only identity evidence.</b> Match นี้ไม่เปลี่ยน Membership / Points / Tier / Access; สิทธิ์ยังอ่านจาก my_mmd_entitlement_resolver_v1 เท่านั้น</div>';
const live=q('[data-mmd-c360-intel]',root),flow=q('.flow',root);if(live)live.insertAdjacentElement('afterend',panel);else flow?.insertAdjacentElement('afterend',panel);
const label={verified_match:'VERIFIED MATCH ✓',review_required:'REVIEW REQUIRED',mismatch:'MISMATCH · REVIEW',insufficient_evidence:'WAITING FOR EVIDENCE',unavailable:'UNAVAILABLE',matched:'MATCHED ✓',ready:'READY',missing:'NO EVIDENCE'};function pretty(v){const k=txt(v);return label[k]||k.replace(/_/g,' ').toUpperCase()||'—'}function tail(v){const x=txt(v);return x?'••••'+esc(x):'—'}function reset(){q('[data-ia-state]',panel).textContent='WAITING';q('[data-ia-state]',panel).className='ia-state';['liff','ofc','client'].forEach(k=>{q('[data-ia-'+k+']',panel).textContent='—';q('[data-ia-'+k+'-tail]',panel).textContent='—'})}
let last='',seq=0;async function load(id){id=txt(id);if(!/^rec[\w]+$/.test(id)){last='';reset();return}if(id===last&&q('[data-ia-state]',panel).textContent!=='UNAVAILABLE')return;last=id;const n=++seq;q('[data-ia-state]',panel).textContent='CHECKING';q('[data-ia-state]',panel).className='ia-state';try{const d=await api(INTEL+'?client_id='+encodeURIComponent(id));if(n!==seq)return;const a=d?.identity?.alignment||{},l=a.liff||{},o=a.line_ofc||{},c=a.canonical_client||{};const s=txt(a.status)||'unavailable';const state=q('[data-ia-state]',panel);state.textContent=pretty(s);state.className='ia-state'+(s==='verified_match'?' good':s==='mismatch'?' bad':'');q('[data-ia-liff]',panel).textContent=pretty(l.status);q('[data-ia-liff-tail]',panel).innerHTML=tail(l.line_tail);q('[data-ia-ofc]',panel).textContent=pretty(o.status);q('[data-ia-ofc-tail]',panel).innerHTML=tail(o.line_tail);q('[data-ia-client]',panel).textContent=pretty(c.status);q('[data-ia-client-tail]',panel).innerHTML=tail(c.line_tail)}catch(e){if(n!==seq)return;reset();q('[data-ia-state]',panel).textContent='UNAVAILABLE'}}
const clientNode=q('[data-client]',root);function sync(){const direct=new URL(location.href).searchParams.get('client_id')||'',visible=txt(clientNode?.textContent);load(/^rec[\w]+$/.test(visible)?visible:direct)}if(clientNode)new MutationObserver(sync).observe(clientNode,{childList:true,characterData:true,subtree:true});root.addEventListener('click',e=>{const b=e.target.closest('[data-action="link_to_client"]');if(b)setTimeout(sync,700)},true);sync();
})();`;
