import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {build} from 'esbuild';
const source=await readFile(new URL('../src/index.ts',import.meta.url),'utf8');
const js=(await build({stdin:{contents:source,loader:'ts',resolveDir:new URL('../src/',import.meta.url).pathname},bundle:true,write:false,format:'esm',platform:'neutral'})).outputFiles[0].text;
const worker=(await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'))).default;
const env={ALLOWED_ORIGINS:'https://www.mmdbkk.com'};
const req=(body,origin='https://www.mmdbkk.com')=>new Request('https://www.mmdbkk.com/v1/partner/line/exchange',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
test('LINE entry is private, branded, and requires explicit login',async()=>{
  const r=await worker.fetch(new Request('https://mmdbkk.com/sigil/model/dashboard/partner-login'),env,{});
  assert.equal(r.status,200);
  assert.equal(r.headers.get('Cache-Control'),'no-store');
  const html=await r.text();
  assert.match(html,/SĪGIL Partner · Private Access/);
  assert.match(html,/Recognized Partner Access/);
  assert.match(html,/Partner Control Layer/);
  assert.match(html,/เข้าสู่ระบบด้วย LINE/);
  assert.match(html,/class="go-arrow"/);
  assert.match(html,/class="line-mark" aria-hidden="true"><\/span>/);
  assert.doesNotMatch(html,/#go\{[^}]*background:var\(--green\)/);
  assert.match(html,/02 · Telegram/);
  assert.match(html,/03 · Verify/);
  assert.match(html,/6ab1323f4e443dd3ce36de09_Yuki%20Dash%20log%20mob\.webp/);
  assert.match(html,/6ab1323f7c4d9e972ff1d3ea_Yuki%20Dash%20log%20desk\.webp/);
  assert.match(html,/<picture>/);
  assert.match(html,/<meta name="robots" content="noindex,nofollow">/);
  assert.match(html,/aria-live="polite"/);
  const inlineScript=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1];
  assert.doesNotMatch(inlineScript,/localStorage|sessionStorage/);
});
test('rejects foreign origin before identity lookup',async()=>{assert.equal((await worker.fetch(req({id_token:'fake'},'https://example.com'),env,{})).status,403);});
test('requires fresh LINE token',async()=>{assert.equal((await worker.fetch(req({}),env,{})).status,401);});
test('rejects wrong LINE channel without Airtable access',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json({aud:'wrong',sub:'U'+'a'.repeat(32)});};try{assert.equal((await worker.fetch(req({id_token:'fake'}),env,{})).status,401);assert.equal(calls,1);}finally{globalThis.fetch=original;}});
