import assert from 'node:assert/strict';import test from 'node:test';
import {fixture,apiModule,MODEL,PARTNER,SESSION,OTHER} from './helpers/partner-fixture.mjs';
const {PARTNER_MODEL_CHANGES:C,MODEL_REFERRALS:R,PARTNER_ASSETS:A}=apiModule;
async function setup(t){const f=await fixture();t.after(f.restore);return f;}
test('dashboard exposes canonical model linkage but no customer name, exact address, or invented agreements',async t=>{const f=await setup(t);let r=await(await f.call('/v1/partner/dashboard')).json();assert.equal(r.jobs[0].model_record_id,MODEL);assert.equal(r.models[0].working_system.system,'bridge');assert.doesNotMatch(JSON.stringify(r),/PRIVATE CLIENT|PRIVATE EXACT/);f.db.Referrals[0].fields[R.commissionType]='';r=await(await f.call('/v1/partner/dashboard')).json();assert.equal(r.models[0].working_system.system,null);});
test('linked formula results are filtered by exact Partner id even with a colliding primary name',async t=>{const f=await setup(t);f.db.Referrals.push({id:'recZZZZZZZZZZZZZZ',fields:{[R.partner]:[OTHER],[R.model]:[OTHER]}});const r=await(await f.call('/v1/partner/dashboard')).json();assert.equal(r.referrals.length,1);});
test('profile is review-only until owner approval and rejects a Partner acting as owner',async t=>{const f=await setup(t);const submit=await f.call('/v1/partner/models/change',{body:{action:'update_profile',model_record_id:MODEL,display_name:'Edited model',height_cm:185,share_with_mmd:true}});assert.equal(submit.status,201);assert.equal(f.db.Models[0].fields[apiModule.MODELS.workingName],'Model QA');const id=(await submit.json()).request_id;assert.equal((await f.call('/v1/partner/admin/model-changes/decision',{body:{request_record_id:id,decision:'approve'}})).status,401);assert.equal((await f.call('/v1/partner/admin/model-changes/decision',{owner:true,body:{request_record_id:id,decision:'approve'}})).status,200);assert.equal(f.db.Models[0].fields[apiModule.MODELS.workingName],'Edited model');});
test('owner accepts a new roster model once without activating public sales or a commission',async t=>{const f=await setup(t);const created=await(await f.call('/v1/partner/models/change',{body:{action:'add_model',display_name:'New QA',age:24,share_with_mmd:true}})).json();const decide=()=>f.call('/v1/partner/admin/model-changes/decision',{owner:true,body:{request_record_id:created.request_id,decision:'approve'}});assert.equal((await decide()).status,200);assert.equal((await(await decide()).json()).idempotent,true);assert.equal(f.db.Models.length,2);assert.equal(f.db.Referrals.length,2);assert.equal(f.db.Models[1].fields.fld9YrnlELxggG6yA,false);assert.equal(f.db.Referrals[1].fields[R.commissionType],undefined);});
test('console relay requires own canonical job and explicit consent',async t=>{const f=await setup(t);assert.equal((await f.call('/v1/partner/models/change',{body:{action:'console_request',session_record_id:SESSION,message:'QA coordination',share_with_mmd:false}})).status,400);f.db.Sessions[0].fields[apiModule.SESSION_FIELDS.partnerIdSnapshot]='partner_other';assert.equal((await f.call('/v1/partner/models/change',{body:{action:'console_request',session_record_id:SESSION,message:'QA coordination',share_with_mmd:true}})).status,403);assert.equal(f.db.Changes.length,0);});
test('private asset list and preview enforce Partner ownership and never disclose keys',async t=>{const f=await setup(t);const asset={id:'recAAAAAAAAAAAAAA',fields:{[A.partner]:[PARTNER],[A.model]:[MODEL],[A.fileName]:'qa.png',[A.fileType]:'image/png',[A.r2Key]:'partner-shared/secret-key'}};f.db.Assets.push(asset);f.objects.set('partner-shared/secret-key',{etag:'image',textValue:'fixture-image'});const r=await(await f.call('/v1/partner/models/assets')).json();assert.equal(r.assets[0].preview_available,true);assert.doesNotMatch(JSON.stringify(r),/secret-key/);let image=await f.call('/v1/partner/models/asset?asset_id='+asset.id);assert.equal(image.status,200);assert.match(image.headers.get('cache-control'),/no-store/);asset.fields[A.partner]=[OTHER];assert.equal((await f.call('/v1/partner/models/asset?asset_id='+asset.id)).status,403);});
test('vault stores only encrypted envelope and rejects stale writes rather than losing private schedules',async t=>{const f=await setup(t);const envelope={version:1,salt:'s'.repeat(22),iv:'i'.repeat(16),ciphertext:'c'.repeat(64)};assert.equal((await f.call('/v1/partner/private-vault',{body:{envelope}})).status,409);let r=await f.call('/v1/partner/private-vault',{body:{envelope,revision:null,private_note:'DO NOT STORE'}});assert.equal(r.status,200);const first=await r.json();assert.doesNotMatch(JSON.stringify([...f.objects.values()]),/DO NOT STORE/);assert.equal((await f.call('/v1/partner/private-vault',{body:{envelope,revision:null}})).status,409);r=await f.call('/v1/partner/private-vault',{body:{envelope,revision:first.revision}});assert.equal(r.status,200);const loaded=await(await f.call('/v1/partner/private-vault')).json();assert.notEqual(loaded.revision,first.revision);});
