import {readFile} from 'node:fs/promises';
import ts from 'typescript';
export const MODEL='recMMMMMMMMMMMMMM',PARTNER='recPPPPPPPPPPPPPP',SESSION='recSSSSSSSSSSSSSS',OTHER='recOOOOOOOOOOOOOO';
const source=await readFile(new URL('../../src/index.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source+'\nexport {generatePartnerToken,sha256Hex,MODEL_PARTNERS,MODEL_REFERRALS,MODELS,SESSION_FIELDS,PARTNER_MODEL_CHANGES,PARTNER_ASSETS,PARTNER_COMMISSIONS,MODEL_OFFER_RULES,PAYMENT_FIELDS};',{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
export const apiModule=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const {default:worker,generatePartnerToken,sha256Hex,MODEL_PARTNERS:P,MODEL_REFERRALS:R,MODELS:M,SESSION_FIELDS:S,PARTNER_MODEL_CHANGES:C,PARTNER_ASSETS:A,PARTNER_COMMISSIONS:L}=apiModule;
export async function fixture(){
  const db={Partners:[{id:PARTNER,fields:{[P.partnerId]:'partner_fixture',[P.partnerName]:'Partner QA',[P.status]:'Active',[P.approvalStatus]:'recognized'}}],Models:[{id:MODEL,fields:{[M.workingName]:'Model QA',[M.heightCm]:180,[M.weightKg]:72,[M.availableNow]:true}}],Referrals:[{id:'recRRRRRRRRRRRRRR',fields:{[R.partner]:[PARTNER],[R.model]:[MODEL],[R.ownershipStatus]:'active',[R.commissionType]:'bridge',[R.commissionRate]:7,[R.approvedAt]:'2026-09-01T00:00:00Z'}}],Sessions:[{id:SESSION,fields:{[S.sessionId]:'session_fixture',[S.partnerIdSnapshot]:'partner_fixture',[S.canonicalModel]:[MODEL],[S.modelName]:'Model QA',[S.startTime]:'2026-09-23T05:00:00Z',[S.endTime]:'2026-09-23T07:00:00Z',[S.paymentStatus]:'pending',[S.clientName]:'PRIVATE CLIENT NAME',[S.locationName]:'PRIVATE EXACT ADDRESS'}}],Changes:[],Rules:[],Assets:[],Commissions:[],Payments:[]};
  const objects=new Map(),writes=[],messages=[];let counter=1;
  const env={TOKEN_SECRET:'fixture-only-token-key',ADMIN_APPROVE_SECRET:'fixture-only-owner-key',AIRTABLE_API_KEY:'fixture-only-airtable-key',AIRTABLE_BASE_ID:'appFixture',AIRTABLE_TABLE_MODEL_PARTNERS:'Partners',AIRTABLE_TABLE_MODELS:'Models',AIRTABLE_TABLE_MODEL_REFERRALS:'Referrals',AIRTABLE_TABLE_SESSIONS:'Sessions',AIRTABLE_TABLE_PARTNER_MODEL_CHANGES:'Changes',AIRTABLE_TABLE_MODEL_OFFER_RULES:'Rules',AIRTABLE_TABLE_PARTNER_ASSETS:'Assets',AIRTABLE_TABLE_PARTNER_COMMISSIONS:'Commissions',AIRTABLE_TABLE_PAYMENTS:'Payments',PARTNER_ASSETS_BUCKET_NAME:'fixture-bucket',ALLOWED_ORIGINS:'https://www.mmdbkk.com',AUTH_SERVICE_PARTNERS_TO_TELEGRAM:'fixture-only-router',TELEGRAM_WORKER:{async fetch(req){messages.push(await req.json());return Response.json({ok:true,telegram:{ok:true}});}},PARTNER_ASSETS:{async get(key){const o=objects.get(key);return o?{...o,body:new Blob([o.textValue]).stream(),text:async()=>o.textValue}:null;},async put(key,value,options={}){const old=objects.get(key),cond=options.onlyIf;if(cond?.etagMatches&&old?.etag!==cond.etagMatches)return null;if(cond?.etagDoesNotMatch==='*'&&old)return null;const o={etag:'etag-'+counter++,textValue:typeof value==='string'?value:'fixture-binary',options};objects.set(key,o);return o;}}};
  const token=await generatePartnerToken(env,PARTNER);db.Partners[0].fields[P.accessTokenHash]=await sha256Hex(token);
  const original=globalThis.fetch;
  globalThis.fetch=async(input,options)=>{const req=input instanceof Request&&!options?input:new Request(input,options),url=new URL(req.url);if(url.hostname!=='api.airtable.com')throw Error('unexpected external fetch');const parts=url.pathname.split('/'),table=decodeURIComponent(parts[3]),id=parts[4];const rows=db[table]||[];
    if(req.method==='GET'){if(id){const row=rows.find(r=>r.id===id);return Response.json(row||{error:'not_found'},{status:row?200:404});}const formula=url.searchParams.get('filterByFormula')||'';let found=rows;if(formula.startsWith('OR(')&&formula.includes('RECORD_ID()'))found=rows.filter(r=>formula.includes(r.id));else if(formula.startsWith('{')){const match=formula.match(/^\{([^}]+)\}='([^']*)'$/);if(match)found=rows.filter(r=>String(r.fields[match[1]]||'')===match[2]);}else if(formula.includes('update_working_system'))found=rows.filter(r=>r.fields[C.action]==='update_working_system'&&r.fields[C.status]==='approved');return Response.json({records:found});}
    const body=await req.json();writes.push({method:req.method,table,id,fields:body.fields});if(req.method==='PATCH'){const row=rows.find(r=>r.id===id);if(!row)throw Error('unknown fixture patch');Object.assign(row.fields,body.fields);return Response.json(row);}if(req.method==='POST'){const row={id:'rec'+String(counter++).padStart(14,'0'),createdTime:new Date().toISOString(),fields:body.fields};rows.push(row);db[table]=rows;return Response.json(row);}throw Error('unexpected fixture mutation');};
  const tasks=[];const ctx={waitUntil(p){tasks.push(p);}};
  async function call(path,{body,owner=false,headers={},method}={}){return worker.fetch(new Request('https://www.mmdbkk.com'+path+(path.includes('?')?'&':'?')+'t='+encodeURIComponent(token),{method:method||(body?'POST':'GET'),headers:{...(body?{'Content-Type':'application/json','Idempotency-Key':'fixture-request-'+counter++}:{}),...(owner?{'x-mmd-admin-secret':env.ADMIN_APPROVE_SECRET}:{}),...headers},body:body?JSON.stringify(body):undefined}),env,ctx);}
  return {db,env,token,objects,writes,messages,call,tasks,restore(){globalThis.fetch=original;}};
}
