<script>
(function(){
  "use strict";
  var root=document.getElementById("mmd-blackcard-confirm");
  if(!root||root.dataset.initialized==="true")return;
  root.dataset.initialized="true";
  var state={selected:null,submitting:false,lastFocus:null};
  var cards=all("[data-companion-card]"),selectedPanel=q("[data-selected-panel]"),context=q("[data-context-section]"),sticky=q("[data-sticky-selection]"),sheet=q("[data-review-sheet]"),success=q("[data-success-view]"),form=q("#bc-preference-form"),note=q("#bc-note"),reason=q("#bc-change-reason"),consent=q("[data-review-consent]"),submit=q("[data-submit-request]"),submitLabel=q("[data-submit-label]"),submitMessage=q("[data-submit-message]"),formError=q("[data-form-error]"),storageKey=draftStorageKey();
  var voices={hito:"Hito ให้ความรู้สึกนิ่งและไว้ใจได้ครับ ถ้านี่คือจังหวะที่คุณต้องการ ผมจะจัดเขาเป็น Preference หลักให้ MMD ดูต่อ",hima:"Hima อบอุ่นและทำให้บรรยากาศเป็นธรรมชาติครับ ถ้าคุณชอบพลังแบบนี้ ผมจะใส่บริบทไว้ให้ชัด",hiro:"Hiro ละเอียดและอ่านสถานการณ์เก่งครับ เหมาะเมื่อคุณให้ความสำคัญกับบทสนทนาและความเข้าใจ ผมจะส่งต่อให้ MMD พิจารณา",hiei:"Hiei สุขุม ชัดเจน และรักษาขอบเขตได้ดีครับ ถ้าความเป็นส่วนตัวสำคัญกับคุณ ผมจะเน้นจุดนี้ไว้ใน Preference"};
  function q(s){return root.querySelector(s)}function all(s){return Array.prototype.slice.call(root.querySelectorAll(s))}function text(s,v){var e=q(s);if(e)e.textContent=v}function param(n){try{return new URL(location.href).searchParams.get(n)||""}catch(e){return""}}function draftStorageKey(){var raw=correlation();if(!raw)return"";var hash=2166136261;for(var i=0;i<raw.length;i++){hash^=raw.charCodeAt(i);hash=Math.imul(hash,16777619)}return"mmd:blackcard-companion:draft:v2:"+((hash>>>0).toString(36))}function clearDraft(){if(!storageKey)return;try{localStorage.removeItem(storageKey)}catch(e){}}function clearLegacyDraft(){try{localStorage.removeItem("mmd:blackcard-companion:draft:v2")}catch(e){}}function flow(){return(root.dataset.currentCompanion||param("mode")==="change")?"change":"first"}function checked(){return all('input[name="preferences"]:checked').map(function(i){return i.value})}
  function isOpaque(value,max){return typeof value==="string"&&value.trim().length>0&&value.trim().length<=max&&!/[\u0000-\u001F\u007F]/.test(value)}
  function correlation(){var value=param("t").trim();return isOpaque(value,512)?value:""}
  function isServerTimestamp(value){return typeof value==="string"&&value.trim().length>0&&!isNaN(Date.parse(value))}
  function isAcceptedResponse(status,data){return status===202&&data&&data.ok===true&&data.status==="pending_review"&&isOpaque(data.request_id,200)&&isServerTimestamp(data.submitted_at)}
  function initImages(){all("[data-profile-image]").forEach(function(img){var key=img.dataset.profileImage,datasetKey=key+"Image",url=root.dataset[datasetKey];if(!url){img.removeAttribute("src");return}img.addEventListener("load",function(){img.classList.add("is-loaded")},{once:true});img.addEventListener("error",function(){img.classList.remove("is-loaded");img.removeAttribute("src")},{once:true});img.src=url;if(img.complete&&img.naturalWidth)img.classList.add("is-loaded")})}
  function setFlow(){var change=flow()==="change";text("[data-flow-label]",change?"Request a Companion Change":"Choose your first Companion");text("[data-review-type]",change?"Companion Change Request":"First Companion Preference");all("[data-change-reason-field]").forEach(function(e){e.hidden=!change});if(submitLabel)submitLabel.textContent=change?"Request Companion Change":"Submit Companion Preference"}
  function choose(card,scroll,persist){if(!card)return;state.selected={id:card.dataset.companion,name:card.dataset.name,role:card.dataset.role,summary:card.dataset.summary};cards.forEach(function(item){var active=item===card,button=item.querySelector("[data-select-companion]"),label=item.querySelector("[data-button-label]");item.classList.toggle("is-selected",active);if(button)button.setAttribute("aria-pressed",String(active));if(label)label.textContent=active?"Selected Preference":"Select "+item.dataset.name});selectedPanel.hidden=false;context.hidden=false;sticky.hidden=false;text("[data-selection-status]","Preference selected");text("[data-selected-role]",state.selected.role.toUpperCase());text("[data-selected-name]",state.selected.name);text("[data-selected-summary]",state.selected.summary);text("[data-ewvon-confirmation]",voices[state.selected.id]);text("[data-sticky-name]",state.selected.name+" · "+state.selected.role);if(persist!==false)save();if(scroll!==false)selectedPanel.scrollIntoView({behavior:"smooth",block:"center"})}
  function clear(){state.selected=null;cards.forEach(function(card){card.classList.remove("is-selected");var b=card.querySelector("[data-select-companion]"),l=card.querySelector("[data-button-label]");if(b)b.setAttribute("aria-pressed","false");if(l)l.textContent="Select "+card.dataset.name});selectedPanel.hidden=true;context.hidden=true;sticky.hidden=true;text("[data-selection-status]","Awaiting your preference");save();q("#bc-companions").scrollIntoView({behavior:"smooth",block:"start"})}
  function payload(){return{request_type:flow()==="change"?"companion_change_request":"first_companion_preference",companion_preference:state.selected?state.selected.id:"",experience_preferences:checked(),note:note.value.trim(),change_reason:reason.value.trim(),current_companion:root.dataset.currentCompanion||"",t:correlation(),source_route:location.pathname,submitted_at:new Date().toISOString()}}
  function validate(){hide(formError);if(!correlation())return fail("ลิงก์คำขอนี้ไม่สมบูรณ์ครับ กรุณากลับไปเปิดลิงก์ล่าสุดจาก MMD");if(!state.selected)return fail("เลือก Companion ที่คุณรู้สึกสบายใจก่อนนะครับ");if(flow()==="change"&&!reason.value.trim())return fail("บอกเหตุผลสั้น ๆ ให้ผมเข้าใจบริบทของ Change Request ก่อนครับ");return true}
  function fail(message){show(formError,message);if(formError)formError.scrollIntoView({behavior:"smooth",block:"center"});return false}
  function review(){if(!validate())return;var prefs=checked(),noteText=note.value.trim(),reasonText=reason.value.trim(),noteRow=q("[data-review-note-row]"),reasonRow=q("[data-review-reason-row]");text("[data-review-name]",state.selected.name+" · "+state.selected.role);text("[data-review-preferences]",prefs.length?prefs.join(" · "):"Not specified");noteRow.hidden=!noteText;reasonRow.hidden=flow()!=="change"||!reasonText;text("[data-review-note]",noteText);text("[data-review-reason]",reasonText);consent.checked=false;submit.disabled=true;hide(submitMessage);state.lastFocus=document.activeElement;sheet.hidden=false;document.documentElement.style.overflow="hidden";requestAnimationFrame(function(){q("[data-close-review]").focus()})}
  function close(){sheet.hidden=true;document.documentElement.style.overflow="";if(state.lastFocus&&state.lastFocus.focus)state.lastFocus.focus()}
  function show(el,message){if(!el)return;el.textContent=message;el.hidden=false}function hide(el){if(!el)return;el.textContent="";el.hidden=true}
  function loading(on){state.submitting=on;submit.disabled=on||!consent.checked;submit.classList.toggle("is-loading",on);submit.setAttribute("aria-busy",String(on));submitLabel.textContent=on?"Sending to MMD...":flow()==="change"?"Request Companion Change":"Submit Companion Preference"}
  function fetchTimeout(url,options,ms){var controller=typeof AbortController==="function"?new AbortController():null,timer;if(controller){options.signal=controller.signal;timer=setTimeout(function(){controller.abort()},ms)}return fetch(url,options).finally(function(){if(timer)clearTimeout(timer)})}
  function parse(res){return res.text().then(function(t){if(!t)return{};try{return JSON.parse(t)}catch(e){return{}}})}
  function send(){if(state.submitting||!state.selected)return;if(!consent.checked)return show(submitMessage,"ยืนยันเงื่อนไขก่อนนะครับ แล้วผมจะส่ง Preference ให้ MMD");if(!correlation())return show(submitMessage,"ลิงก์คำขอนี้ไม่สมบูรณ์ครับ กรุณากลับไปเปิดลิงก์ล่าสุดจาก MMD");var endpoint=(root.dataset.submitEndpoint||"").trim();if(!endpoint)return show(submitMessage,"ตอนนี้ช่องทางส่งคำขอยังไม่พร้อมครับ กรุณาติดต่อ MMD เพื่อดำเนินการต่อ");var url;try{url=new URL(endpoint,location.origin)}catch(e){return show(submitMessage,"Submission Endpoint ไม่ถูกต้อง กรุณาตรวจสอบการตั้งค่าครับ")}if(url.origin!==location.origin)return show(submitMessage,"Submission Endpoint ต้องเป็นช่องทางของ MMD บนโดเมนนี้เท่านั้นครับ");loading(true);hide(submitMessage);fetchTimeout(url.href,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},credentials:"same-origin",body:JSON.stringify(payload())},15000).then(function(res){return parse(res).then(function(data){if(!isAcceptedResponse(res.status,data))throw new Error((!res.ok&&(data.message||data.error))||"MMD ยังไม่สามารถยืนยันการรับคำขอได้ กรุณาลองอีกครั้งครับ");return data})}).then(function(){clearDraft();close();success.hidden=false;document.documentElement.style.overflow="hidden";var link=q("[data-success-link]"),target=new URL(root.dataset.successUrl||"/blackcard/black-card",location.origin),token=param("t");if(token)target.searchParams.set("t",token);link.href=target.pathname+target.search+target.hash;link.focus()}).catch(function(e){show(submitMessage,e&&e.name==="AbortError"?"ใช้เวลานานกว่าปกติครับ กรุณาตรวจสอบอินเทอร์เน็ตแล้วลองใหม่":e.message||"เกิดปัญหาระหว่างส่งคำขอ กรุณาลองอีกครั้งครับ")}).finally(function(){loading(false)})}
  function save(){if(!storageKey)return;var draft={selected:state.selected?state.selected.id:"",preferences:checked(),note:note.value,reason:reason.value,savedAt:Date.now()};try{localStorage.setItem(storageKey,JSON.stringify(draft))}catch(e){}}
  function restore(){if(!storageKey)return;var d;try{d=JSON.parse(localStorage.getItem(storageKey)||"null")}catch(e){return}if(!d||typeof d.savedAt!=="number"||Date.now()-d.savedAt>604800000){clearDraft();return}if(d.selected){var card=cards.find(function(c){return c.dataset.companion===d.selected});if(card)choose(card,false,false)}if(Array.isArray(d.preferences))all('input[name="preferences"]').forEach(function(i){i.checked=d.preferences.indexOf(i.value)!==-1});if(typeof d.note==="string")note.value=d.note;if(typeof d.reason==="string")reason.value=d.reason;counts()}
  function counts(){text("[data-character-count]",String(note.value.length));text("[data-reason-count]",String(reason.value.length))}
  function trap(e){if(sheet.hidden||e.key!=="Tab")return;var items=Array.prototype.slice.call(sheet.querySelectorAll('button:not([disabled]),input:not([disabled]),[href],[tabindex]:not([tabindex="-1"])'));if(!items.length)return;var first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
  all("[data-scroll-to-companions]").forEach(function(b){b.addEventListener("click",function(){q("#bc-companions").scrollIntoView({behavior:"smooth",block:"start"})})});cards.forEach(function(c){c.querySelector("[data-select-companion]").addEventListener("click",function(){choose(c,true)})});all("[data-change-selection]").forEach(function(b){b.addEventListener("click",clear)});all("[data-open-review]").forEach(function(b){b.addEventListener("click",review)});all("[data-close-review]").forEach(function(b){b.addEventListener("click",close)});
  form.addEventListener("submit",function(e){e.preventDefault();hide(formError);review()});form.addEventListener("change",save);note.addEventListener("input",function(){counts();save()});reason.addEventListener("input",function(){counts();save()});consent.addEventListener("change",function(){submit.disabled=state.submitting||!consent.checked;hide(submitMessage)});submit.addEventListener("click",send);document.addEventListener("keydown",function(e){if(e.key==="Escape"&&!sheet.hidden){close();return}trap(e)});
  initImages();setFlow();clearLegacyDraft();restore();counts();
})();
</script>
