import test from "node:test";
import assert from "node:assert/strict";
import { handleKenjiLineMemberTruth } from "../src/kenji-line-member-truth.js";
const uid = `U${"3".repeat(32)}`;
function request() { return new Request("https://member-pages-worker.internal/__internal/kenji/member-truth", { method:"POST", headers:{"content-type":"application/json","x-mmd-internal-call":"true","x-mmd-service-binding":"member-dashboard-chat-worker"}, body:JSON.stringify({line_user_id:uid,intent:"rights_check"}) }); }
function fixture({level="private_premium", lifecycle="active", expire="2028-10-01", corrupt=false, category="service", otherMember=false, duplicatePayment=false, recovery="reconciled"}={}) {
  const now = new Date().toISOString(); const amount = corrupt ? 6132082 : 10000; const points = corrupt ? 61320 : 100;
  const snapshot = { schema_version:"my_mmd_entitlement_resolver_v1",source_status:"verified",fail_closed:true,evaluated_at:now,member_blocked:false,
    capability_state:{active:lifecycle==="active"?[level]:[],inactive:lifecycle==="expired"?[level]:[],recognized:[level]},access:{private_visibility_envelope:"premium",public_service_access:true},
    entitlements:[{capability:level,lifecycle,expire_at:expire}] };
  const rows = [{id:"fixture-ledger",fields:{member_id:otherMember?"another-member":"fixture-member",points,eligible_amount_thb:amount,payment_ref:"fixture-paid",session_id:"fixture-service",transaction_status:"posted",posted_at:now}}];
  const paid = {id:"fixture-payment",fields:{member_id:"fixture-member","Payment Reference":"fixture-paid","Payment Status":"paid","Verification Status":"verified",Amount:corrupt?10000:amount,session_id:"fixture-service",payment_kind:category}};
  const reads=[];
  const env={AIRTABLE_API_KEY:"fixture",AIRTABLE_BASE_ID:"fixture-base",MEMBER_STATUS_RESOLVER_SECRET:"f".repeat(40), LIFF_IDENTITY_KV:{get:async()=>({state:recovery})},
    MEMBER_STATUS_RESOLVER:{fetch:async req=>{assert.equal((await req.json()).line_user_id,uid);return Response.json({ok:true,data:{member_exists:true,member_id:"fixture-member",profile:{customer_360:{points:{status:"verified",active_points:61320}}},entitlement_snapshot:snapshot}});}},
    AIRTABLE_HTTP:{fetch:async req=>{ assert.equal(req.method,"GET"); const url=new URL(req.url);const table=url.pathname.split("/").pop();reads.push(url);if(table==="tblgWc5VRon5o8Mhk")return Response.json({records:[{id:"fixture-member-row",fields:{member_id:"fixture-member","Contact Email":"owner-fixture@example.invalid"}}]});if(table==="tbl5dfnwjUFMLbnWL")return Response.json({records:rows});if(table==="tblWGGJJOx5eBvBZJ")return Response.json({records:duplicatePayment?[paid,{...paid,id:"other-payment"}]:[paid]});throw new Error(`unexpected table ${table}`);}}};
  return {env,reads};
}
test("rights truth uses own canonical paid balance and guarded spend for quote",async()=>{const f=fixture();const r=await handleKenjiLineMemberTruth(request(),f.env);assert.equal(r.status,200);const data=await r.json();assert.equal(data.points.active_points,100);assert.equal(data.points.authority,"canonical_paid_points_source_guard_v1");assert.equal(data.renewal.status,"ready");assert.equal(data.renewal.amount_thb,2500);const ledger=f.reads.find(x=>x.pathname.endsWith("tbl5dfnwjUFMLbnWL"));assert.match(ledger.searchParams.get("filterByFormula"),/member_id/);assert.doesNotMatch(ledger.searchParams.get("filterByFormula"),/email/);});
for(const options of [{corrupt:true},{otherMember:true},{duplicatePayment:true},{recovery:"review_required"}]) test(`uncertain source stays pending ${JSON.stringify(options)}`,async()=>{const f=fixture(options);const data=await(await handleKenjiLineMemberTruth(request(),f.env)).json();assert.equal(data.points.active_points,null);assert.equal(data.renewal.status,"review_required");assert.equal(data.membership.level,"private_premium");});
test("missing service classification never derives discount from notes",async()=>{const f=fixture({category:""});const data=await(await handleKenjiLineMemberTruth(request(),f.env)).json();assert.equal(data.points.active_points,100);assert.equal(data.renewal.status,"review_required");});
for(const level of ["vip","svip","black_card"]) test(`canonical ${level} never downgraded`,async()=>{const f=fixture({level});const data=await(await handleKenjiLineMemberTruth(request(),f.env)).json();assert.equal(data.membership.level,level);assert.equal(data.renewal.reason,"protected_tier_owner_review");});
test("long expired member classified as new signup without granting rights",async()=>{const f=fixture({lifecycle:"expired",expire:"2024-09-01"});const data=await(await handleKenjiLineMemberTruth(request(),f.env)).json();assert.equal(data.renewal.classification,"new_signup");assert.equal(data.membership.lifecycle,"expired");});
test("ordinary HTTP host cannot use internal rights truth",async()=>{const f=fixture();const req=request();const invalid=new Request("https://mmdbkk.com/__internal/kenji/member-truth",req);assert.equal((await handleKenjiLineMemberTruth(invalid,f.env)).status,404);assert.equal(f.reads.length,0);});
