import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {preparePrivatePreviewDataset} from '../src/own-history-preview.mjs';
import {handleMemberHistoryPreview, HISTORY_PREVIEW_PATH} from '../src/member-history-preview.js';
const A='U'+'a'.repeat(32), B='U'+'b'.repeat(32), C='U'+'c'.repeat(32);
function fixture() {return {schemaVersion:1,sourceBasis:'saved_oa_job_notes_recorded_estimate',scope:'client_and_purchased_snapshot',pointsBaselineTHBPerPoint:100,noExpiryOrDeductionsApplied:true,datasetId:'fixture',asOfDate:'2026-10-02',windowStart:'2023-10-02',windowEnd:'2026-10-02',customersByLineUid:{[A]:{displayName:'Fixture',recordedHistoryAmountTHB:1250,estimatedGrossPointsBeforeDeduction:12.5,historyState:'preliminary_review',redemptionEnabled:false,automaticPrivilegeEnabled:false},[B]:{displayName:'Fixture B',recordedHistoryAmountTHB:null,estimatedGrossPointsBeforeDeduction:null,historyState:'identity_review',redemptionEnabled:false,automaticPrivilegeEnabled:false}}};}
async function prepare(data=fixture()){const raw=JSON.stringify(data),hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));return preparePrivatePreviewDataset(raw,Array.from(new Uint8Array(hash),x=>x.toString(16).padStart(2,'0')).join(''));}
const req=(suffix='',init={})=>new Request('https://mmdbkk.com'+HISTORY_PREVIEW_PATH+suffix,init);
test('own-session preview returns only whitelisted own estimate, never identity index or privileges',async()=>{const preview=await prepare();const response=await handleMemberHistoryPreview(req(),{}, {readSession:async()=>({lineUserId:A,memberProfile:{tier:'SVIP'}}),loadPreview:async()=>preview});const body=await response.json();assert.equal(response.status,200);assert.equal(body.data.estimatedGrossPointsBeforeDeduction,12.5);assert.equal(body.data.redemptionEnabled,false);assert.equal(body.data.automaticPrivilegeEnabled,false);assert.equal(body.data.noExpiryOrDeductionsApplied,true);assert.equal(body.data.notice,"ข้อมูลยังแสดงไม่ครบ");assert.equal(body.data.fieldStatus.points,"provisional");assert.equal(body.data.historyCompleteness,"partial");assert.equal(body.data.amountMeaning,'recorded_job_estimate_not_verified_paid');assert.doesNotMatch(JSON.stringify(body),/customersByLineUid|lineUserId|SVIP/);assert.match(response.headers.get('cache-control'),/private, no-store/);});
test('missing/expired session, client UID, cross-origin and writes cannot read private preview',async()=>{let loads=0;const dependencies={readSession:async()=>null,loadPreview:async()=>{loads++;return prepare();}};assert.equal((await handleMemberHistoryPreview(req(),{},dependencies)).status,401);assert.equal((await handleMemberHistoryPreview(req('?lineUserId='+A),{},dependencies)).status,400);assert.equal((await handleMemberHistoryPreview(req('',{headers:{origin:'https://other.example'}}),{},dependencies)).status,403);assert.equal((await handleMemberHistoryPreview(req('',{method:'POST'}),{},dependencies)).status,405);assert.equal(loads,0);});
test('real session expiration is enforced before reading the private KV dataset',async()=>{const reads=[];const env={LIFF_SESSION_SECRET:'fixture-only-secret-with-more-than-32-chars',LIFF_IDENTITY_KV:{get:async key=>{reads.push(key);return {line_user_id:A,expires_at:Date.now()-1};}}};assert.equal((await handleMemberHistoryPreview(req('',{headers:{cookie:'__Host-mmd_liff_session=fixture-token'}}),env)).status,401);assert.equal(reads.length,1);assert.match(reads[0],/^liff:session:/);});
test('unknown and quarantined identities return no zero balance or fallback from another customer',async()=>{const preview=await prepare();for(const [uid,status] of [[B,200],[C,404]]){const response=await handleMemberHistoryPreview(req(),{}, {readSession:async()=>({lineUserId:uid}),loadPreview:async()=>preview});const body=await response.json();assert.equal(response.status,status);if(body.data){assert.equal(body.data.recordedHistoryAmountTHB,null);assert.equal(body.data.estimatedGrossPointsBeforeDeduction,null);}else assert.equal(body.data,null);}});
test('unprovisioned data and bad checksum remain pending without any writes or ledger fallback',async()=>{const session={readSession:async()=>({lineUserId:A})};for(const env of [{},{LIFF_IDENTITY_KV:{get:async()=>JSON.stringify(fixture())}}]){const response=await handleMemberHistoryPreview(req(),env,session);assert.equal(response.status,503);assert.equal((await response.json()).data,null);}await assert.rejects(preparePrivatePreviewDataset(JSON.stringify(fixture()),'0'.repeat(64)),/checksum/);const bad=fixture();bad.customersByLineUid[A].redemptionEnabled=true;await assert.rejects(prepare(bad),/invalid/);});
test('HEAD has no private body and lookup rejects client assertions',async()=>{const preview=await prepare();assert.equal(preview.lookupOwnHistory({provider:'line',isVerified:false,lineUserId:A}).statusCode,401);const r=await handleMemberHistoryPreview(req('',{method:'HEAD'}),{}, {readSession:async()=>({lineUserId:A}),loadPreview:async()=>preview});assert.equal(r.status,200);assert.equal(await r.text(),'');});
test('LIFF estimate rendering clears stale account amounts on failures/reload and never updates spendable points',async()=>{const source=readFileSync(new URL('../src/liff-member-shell.js',import.meta.url),'utf8');const code=source.slice(source.indexOf('  let memberApiChain'),source.indexOf('  async function readQuickMembershipStatus()'));const nodes=Object.fromEntries(['history-preview-points','history-preview-amount','history-preview-notice','profile-points','profile-tier'].map(id=>[id,{textContent:id==='profile-tier'?'SVIP':'stale'}]));let data=(await prepare()).lookupOwnHistory({provider:'line',isVerified:true,lineUserId:A}).data;let status=200;const context=vm.createContext({setTimeout,document:{getElementById:id=>nodes[id]},fetch:async()=>Response.json({ok:status===200,data},{status}),Intl,formatThb:v=>v+' THB'});vm.runInContext(code,context);await context.readOwnHistoryPreview();assert.equal(nodes['history-preview-points'].textContent,'12.5 คะแนนประมาณการ');assert.equal(nodes['profile-points'].textContent,'stale');assert.equal(nodes['profile-tier'].textContent,'SVIP');status=401;await context.readOwnHistoryPreview();assert.equal(nodes['history-preview-points'].textContent,'—');assert.equal(nodes['history-preview-amount'].textContent,'');status=200;data={...data,historyState:'identity_review',recordedHistoryAmountTHB:null,estimatedGrossPointsBeforeDeduction:null};await context.readOwnHistoryPreview();assert.equal(nodes['history-preview-points'].textContent,'—');assert.match(nodes['history-preview-notice'].textContent,/การเชื่อมบัญชี/);});
test('late response from an earlier preview read cannot restore stale history after session failure',async()=>{const source=readFileSync(new URL('../src/liff-member-shell.js',import.meta.url),'utf8');const code=source.slice(source.indexOf('  let memberApiChain'),source.indexOf('  async function readQuickMembershipStatus()'));const nodes=Object.fromEntries(['history-preview-points','history-preview-amount','history-preview-notice'].map(id=>[id,{textContent:'stale'}]));let release;const delayed=new Promise(resolve=>{release=resolve;});let calls=0;const context=vm.createContext({setTimeout,document:{getElementById:id=>nodes[id]},fetch:async()=>++calls===1?delayed:Response.json({ok:false},{status:401}),Intl,formatThb:v=>v+' THB'});vm.runInContext(code,context);const first=context.readOwnHistoryPreview();await context.readOwnHistoryPreview();const data=(await prepare()).lookupOwnHistory({provider:'line',isVerified:true,lineUserId:A}).data;release(Response.json({ok:true,data}));await first;assert.equal(nodes['history-preview-points'].textContent,'—');assert.equal(nodes['history-preview-amount'].textContent,'');});
test('one own provisional estimate displays without expiry or full profile, and missing points never erase supported expiry',async()=>{
  const source=readFileSync(new URL('../src/liff-member-shell.js',import.meta.url),'utf8');assert.match(source,/ข้อมูลยังแสดงไม่ครบ/);
  const code=source.slice(source.indexOf('  let memberApiChain'),source.indexOf('  async function readQuickMembershipStatus()'));
  const nodes=Object.fromEntries(['history-preview-points','history-preview-amount','history-preview-notice','minimal-member-points','minimal-member-expiry','minimal-member-display'].map(id=>[id,{textContent:id==='minimal-member-expiry'?'2028-08-21':'—',hidden:true}]));
  let status=200;let data=(await prepare()).lookupOwnHistory({provider:'line',isVerified:true,lineUserId:A}).data;
  const context=vm.createContext({setTimeout,document:{getElementById:id=>nodes[id]},fetch:async()=>Response.json({ok:status===200,data},{status}),Intl,formatThb:v=>v+' THB'});vm.runInContext(code,context);
  await context.readOwnHistoryPreview();assert.equal(nodes['minimal-member-display'].hidden,false);assert.equal(nodes['minimal-member-points'].textContent,'12.5 คะแนนประมาณการ');assert.equal(nodes['minimal-member-expiry'].textContent,'2028-08-21');
  data={...data,historyState:'identity_review',recordedHistoryAmountTHB:null,estimatedGrossPointsBeforeDeduction:null};await context.readOwnHistoryPreview();assert.equal(nodes['minimal-member-points'].textContent,'—');assert.equal(nodes['minimal-member-expiry'].textContent,'2028-08-21');
  status=503;await context.readOwnHistoryPreview();assert.equal(nodes['minimal-member-expiry'].textContent,'2028-08-21');
});
